### ISSUE TITLE
npm install  报错 无法安装依赖 node 

### ISSUE THREAD

**Issue by howold-lab** [ruochuan12/axios-analysis#1]
![image](https://user-images.githubusercontent.com/71859711/197099372-09ea98b3-9eb2-4f32-802f-006e503689be.png)

**Comment by ruochuan12** [comment]
是什么版本的 `node` 、`npm` 呢。

具体操作可以详细描述下，在哪个路径安装的~

**Comment by howold-lab** [comment]
![image](https://user-images.githubusercontent.com/71859711/197459985-0eb131ba-d810-4d83-adb9-f997271db2d3.png)
![image](https://user-images.githubusercontent.com/71859711/197460067-1feddf6e-ebf5-4ae2-9770-8ee59b81b371.png)

node 版本16.0.0 npm 7.10.0 安装路径 D:\gitcode\axios-analysis\axios> 路径在图片第一张体现出来 
目前node 版本有限制？

**Comment by ruochuan12** [comment]
建议切换下 `node` 版本，这是比较久前的 `axios` 。报错中也提示了 `karma` 报错版本相关。

**Comment by howold-lab** [comment]
有建议的node 版本吗

**Comment by ruochuan12** [comment]
试试 12
